version: '3'

services:
  advanced_node:
    image: advanced_node
    volumes:
      - ./:/root
    working_dir: /root

  run:
    image: node:8.14.0
    volumes:
      - ./:/root
      - /root/.git
      - /root/frontend/node_modules
    working_dir: /root/frontend
    ports:
      - 3000:3000
    command: yarn start

  npm:
    image: node:8.14.0
    volumes:
      - ./:/root
      - /root/.git
    working_dir: /root/frontend
    ports:
      - 3000:3000
    entrypoint: npm
